# Generated by Django 4.2.16 on 2025-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField()),
                ('guests', models.IntegerField()),
                ('table_size', models.CharField(choices=[('large', 'LARGE'), ('medium', 'MEDIUM'), ('small', 'SMALL')], max_length=40)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_create', models.DateField()),
            ],
        ),
    ]
