# Generated by Django 5.1.5 on 2025-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('Main', 'MAIN'), ('Starter', 'STARTER'), ('Dessert', 'DESSERT'), ('Drink', 'DRINK')], default='Main', max_length=7),
        ),
    ]
