# Generated by Django 4.2.16 on 2025-02-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestrauntApp', '0002_alter_fooditem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table_booking',
            name='date_create',
        ),
    ]
